site_name: My Site
docs_dir: dev_site/docs

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select


nav:
  - Home: index.md
  - Hello: hello.md
  - Tutorials:
        - Bar Chart: tutorials/bar_chart/bar_chart.md

plugins:
  - typeset
  - search

markdown_extensions:
  # Built-in Markdown extensions
  - abbr
  - attr_list
  - footnotes

  # Python Markdown extensions
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.highlight:
      line_spans: __span
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
      base_path: docs_src
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true

  # Material theme extensions
  - material.extensions.preview:
      targets:
        include:
          - "*"
