version: '3'
services:
  nginx:
    image: nginx
    networks:
      - analytics_network
  mkdocs-dev:
    image: ghcr.io/analyticsbymark/mkdocs-material-insiders
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs  # Mount dev site folder
      - ./dev_site/mkdocs.yml:/docs/mkdocs.yml  # Override mkdocs.yml
    stdin_open: true
    tty: true

  mkdocs-blog:
    image: ghcr.io/analyticsbymark/mkdocs-material-insiders
    ports:
      - "8006:8000"
    volumes:
      - ./blog_site:/docs  # Mount blog site folder
      - ./blog_site/mkdocs.yml:/docs/mkdocs.yml  # Override mkdocs.yml
    stdin_open: true
    tty: true
  frontend:
    image: 'plotly:${TAG-latest}'#
    networks:
      - analytics_network
    ports:
      - "8056:8056"
      - "8050:8050"
    restart: on-failure
    build:
      context: .

networks:
  analytics_network:
