name: Deploy to Production

on:
  release:
    types:
      - published
    workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on:
      - self-hosted
      - production
    env:
      ENVIRONMENT: production
      DOMAIN: https://analyticsbymark.co.uk
      STACK_NAME: analyticsbymark
      INSIDERS_LOGIN: ${{ secrets.INSIDERS_LOGIN }}
      INSIDERS_TOKEN: ${{ secrets.INSIDERS_TOKEN }}
    steps:
      - name: Login to GitHub Container Registry
      - run: echo ${{ secrets.INSIDERS_LOGIN }} | docker login ghcr.io -u ${{ secrets.INSIDERS_TOKEN }} --password-stdin
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml --project-name analyticsbymark build
      - run: docker compose -f docker-compose.yml --project-name analyticsbymark up -d