name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
      fail-fast: false
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        # Allow debugging with tmate
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v3
          if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
          with:
            limit-access-to-actor: true
        - uses: actions/cache@v4
          id: cache
          with:
            path: ${{ env.pythonLocation }}
            key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('requirements-tests.txt') }}-v01
        - name: Install Dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: |
              pwd
              ls -la
              pip install -r requirements-tests.txt
        - name: Lint
          run: bash scripts/lint.sh
        - run: mkdir coverage
        - name: Test
          run: bash scripts/test.sh
          env:
            COVERAGE_FILE: coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}
            CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}
        - name: Store coverage files
          uses: actions/upload-artifact@v4
          with:
            name: coverage-${{ matrix.python-version }}-${{ matrix.pydantic-version }}
            path: coverage